# Generated by Django 4.1 on 2025-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
