# Generated by Django 4.1 on 2025-10-23 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default="default", max_length=20),
            preserve_default=False,
        ),
    ]
