# Generated by Django 4.1 on 2025-10-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Gender',
            new_name='gender',
        ),
    ]
